"""initial schema"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "20260502_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table("roles", sa.Column("name", sa.String(64), nullable=False), sa.Column("description", sa.String(255)), sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.PrimaryKeyConstraint("id"))
    op.create_table("permissions", sa.Column("name", sa.String(120), nullable=False), sa.Column("code", sa.String(120), nullable=False), sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.PrimaryKeyConstraint("id"))
    op.create_table("political_parties", sa.Column("name", sa.String(180), nullable=False), sa.Column("abbreviation", sa.String(32), nullable=False), sa.Column("founded_year", sa.Integer()), sa.Column("ideology", sa.String(180)), sa.Column("headquarters", sa.String(255)), sa.Column("president", sa.String(180)), sa.Column("description", sa.Text()), sa.Column("total_members", sa.Integer()), sa.Column("website", sa.String(255)), sa.Column("logo_url", sa.String(500)), sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.Column("deleted_at", sa.DateTime(timezone=True)), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("abbreviation"), sa.UniqueConstraint("name"))
    op.create_table("constituencies", sa.Column("name", sa.String(180), nullable=False), sa.Column("state", sa.String(120), nullable=False), sa.Column("type", sa.String(60), nullable=False), sa.Column("population", sa.Integer()), sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.Column("deleted_at", sa.DateTime(timezone=True)), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("name", "state", "type", name="uq_constituency_identity"))
    op.create_table("role_permissions", sa.Column("role_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("permission_id", postgresql.UUID(as_uuid=True), nullable=False), sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("role_id", "permission_id"))
    op.create_table("users", sa.Column("name", sa.String(160), nullable=False), sa.Column("email", sa.String(255), nullable=False), sa.Column("hashed_password", sa.String(255), nullable=False), sa.Column("role_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("token_version", sa.Integer(), nullable=False), sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["role_id"], ["roles.id"]), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("email", name="uq_users_email"))
    op.create_table("politicians", sa.Column("full_name", sa.String(180), nullable=False), sa.Column("age", sa.Integer()), sa.Column("gender", sa.String(32)), sa.Column("political_party_id", postgresql.UUID(as_uuid=True)), sa.Column("constituency_id", postgresql.UUID(as_uuid=True)), sa.Column("current_position", sa.String(180)), sa.Column("education", sa.String(255)), sa.Column("assets_declared", sa.Numeric(14, 2)), sa.Column("criminal_cases", sa.Integer()), sa.Column("image_url", sa.String(500)), sa.Column("bio", sa.Text()), sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.Column("deleted_at", sa.DateTime(timezone=True)), sa.ForeignKeyConstraint(["constituency_id"], ["constituencies.id"]), sa.ForeignKeyConstraint(["political_party_id"], ["political_parties.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("elections", sa.Column("election_name", sa.String(220), nullable=False), sa.Column("election_type", sa.String(80), nullable=False), sa.Column("year", sa.Integer(), nullable=False), sa.Column("state", sa.String(120)), sa.Column("total_seats", sa.Integer(), nullable=False), sa.Column("winning_party_id", postgresql.UUID(as_uuid=True)), sa.Column("turnout_percentage", sa.Numeric(5, 2)), sa.Column("status", sa.String(40), nullable=False), sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.Column("deleted_at", sa.DateTime(timezone=True)), sa.ForeignKeyConstraint(["winning_party_id"], ["political_parties.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("alliances", sa.Column("alliance_name", sa.String(180), nullable=False), sa.Column("description", sa.Text()), sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.Column("deleted_at", sa.DateTime(timezone=True)), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("alliance_name"))
    op.create_table("political_news", sa.Column("title", sa.String(260), nullable=False), sa.Column("content", sa.Text(), nullable=False), sa.Column("source", sa.String(160), nullable=False), sa.Column("published_at", sa.DateTime(timezone=True), nullable=False), sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.Column("deleted_at", sa.DateTime(timezone=True)), sa.PrimaryKeyConstraint("id"))
    op.create_table("alliance_members", sa.Column("alliance_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("party_id", postgresql.UUID(as_uuid=True), nullable=False), sa.ForeignKeyConstraint(["alliance_id"], ["alliances.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["party_id"], ["political_parties.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("alliance_id", "party_id"))
    op.create_table("election_results", sa.Column("election_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("constituency_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("politician_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("party_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("votes_received", sa.Integer(), nullable=False), sa.Column("vote_percentage", sa.Numeric(5, 2), nullable=False), sa.Column("won", sa.Boolean(), nullable=False), sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.Column("deleted_at", sa.DateTime(timezone=True)), sa.ForeignKeyConstraint(["constituency_id"], ["constituencies.id"]), sa.ForeignKeyConstraint(["election_id"], ["elections.id"]), sa.ForeignKeyConstraint(["party_id"], ["political_parties.id"]), sa.ForeignKeyConstraint(["politician_id"], ["politicians.id"]), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("election_id", "constituency_id", "politician_id", name="uq_result_candidate_constituency"))
    op.create_table("audit_logs", sa.Column("user_id", postgresql.UUID(as_uuid=True)), sa.Column("action", sa.String(80), nullable=False), sa.Column("entity_type", sa.String(120), nullable=False), sa.Column("entity_id", postgresql.UUID(as_uuid=True)), sa.Column("old_value", postgresql.JSONB()), sa.Column("new_value", postgresql.JSONB()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False), sa.ForeignKeyConstraint(["user_id"], ["users.id"]), sa.PrimaryKeyConstraint("id"))
    for table, cols in {
        "roles": ["name"], "permissions": ["code"], "users": ["email", "is_active"],
        "political_parties": ["name", "abbreviation", "ideology", "president", "deleted_at"],
        "constituencies": ["name", "state", "type", "deleted_at"], "politicians": ["full_name", "political_party_id", "constituency_id", "current_position", "deleted_at"],
        "elections": ["election_name", "election_type", "year", "state", "winning_party_id", "status", "deleted_at"],
        "election_results": ["election_id", "constituency_id", "politician_id", "party_id", "won", "deleted_at"],
        "political_news": ["title", "source", "published_at", "deleted_at"], "audit_logs": ["user_id", "action", "entity_type", "entity_id", "created_at"],
    }.items():
        for col in cols:
            op.create_index(f"ix_{table}_{col}", table, [col])
    op.create_index("ix_parties_name_trgm", "political_parties", ["name"], postgresql_using="gin", postgresql_ops={"name": "gin_trgm_ops"})
    op.create_index("ix_politicians_name_trgm", "politicians", ["full_name"], postgresql_using="gin", postgresql_ops={"full_name": "gin_trgm_ops"})
    op.create_index("ix_elections_year_state_type", "elections", ["year", "state", "election_type"])
    op.create_index("ix_results_constituency_won", "election_results", ["constituency_id", "won"])


def downgrade() -> None:
    for table in ["audit_logs", "election_results", "alliance_members", "political_news", "alliances", "elections", "politicians", "users", "role_permissions", "constituencies", "political_parties", "permissions", "roles"]:
        op.drop_table(table)
